version: '3.8'

services:
  app:
    image: nullstone/node:local
    command: ["yarn", "start:server"]
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - node_modules:/app/node_modules
      - next-cache:/app/.next
      - .:/app

volumes:
  node_modules: {}
  next-cache: {}