version: '3.8'

services:
  app:
    image: nullstone/node:local
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000

volumes:
  node_modules: {}
